version: '3.8'

services:
  ubuntu-ansible:
    build: .
    ports:
      - "${SSH_PORT:-2222}:22"
      - "${NGINX_PORT:-8080}:80"
      - "${NODE_PORT:-3000}:3000"
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./Back:/var/www/node-app
      - ./front/dist:/var/www/vue-app
      - mongodb_data:/data/db
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://localhost:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mongodb_data: 