---
- name: "Update repositories cache"
  ansible.builtin.apt:
    update_cache: true
- name: "Install nodejs"
  ansible.builtin.apt:
    name: nodejs
- name: "Install npm"
  ansible.builtin.apt:
    name: npm


- name: Install PM2 globally
  npm:
    name: pm2
    global: yes 