---
- name: Create app directory
  file:
    path: /var/www/{{ hostname }}
    state: directory
    mode: '0755'

- name: Clone application repository
  git:
    repo: "{{ app_repository }}"
    dest: /var/www/{{ hostname }}

- name: Install back npm dependencies
  npm:
    path: /var/www/{{ hostname }}/Back
    state: present

- name: Install front npm dependencies
  npm:
    path: /var/www/{{ hostname }}/front
    state: present

- name: Build back application
  command:
    cmd: npm run build
    chdir: /var/www/{{ hostname }}/Back

- name: Build front application
  command:
    cmd: npm run build
    chdir: /var/www/{{ hostname }}/front

- name: Start application with PM2
  command:
    cmd: pm2 start npm --name "{{ hostname }}" -- start
    chdir: /var/www/{{ hostname }}/Back