---
- hosts: all
  become: yes
  roles:
    - common          # Installation des dépendances de base
    - mongodb         # Installation et configuration de MongoDB
    - nginx           # Installation et configuration de Nginx
    - nodejs         # Installation de Node.js
    - app            # Déploiement de l'application