# Nginx configuration
http_port: 80
proxy_connect_timeout: 60
proxy_send_timeout: 60
proxy_read_timeout: 60

# Hostnames
full_front_hostname: "example1.com"
full_back_hostname: "example2.com"

# Node.js configuration
nodejs_version: "18.x"
node_port: 3000

# Application paths
node_app_path: /var/www/node-app
vue_app_path: /var/www/vue-app

# MongoDB configuration
mongodb_version: "6.0"
mongodb_port: 27017
mongodb_user: "appuser"
mongodb_password: "{{ vault_mongodb_password }}"
mongodb_database: "appdb"

# Nginx paths
nginx_sites_enabled: /etc/nginx/sites-enabled
nginx_sites_available: /etc/nginx/sites-available 