---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy node backend configuration
  template:
    src: node.conf.j2
    dest: "{{ nginx_sites_available }}/{{ full_back_hostname }}.conf"
    mode: '0644'
  notify: restart nginx

- name: Copy vue frontend configuration
  template:
    src: vue.conf.j2
    dest: "{{ nginx_sites_available }}/{{ full_front_hostname }}.conf"
    mode: '0644'
  notify: restart nginx

- name: Enable node configuration
  file:
    src: "{{ nginx_sites_available }}/{{ full_back_hostname }}.conf"
    dest: "{{ nginx_sites_enabled }}/{{ full_back_hostname }}.conf"
    state: link
  notify: restart nginx

- name: Enable vue configuration
  file:
    src: "{{ nginx_sites_available }}/{{ full_front_hostname }}.conf"
    dest: "{{ nginx_sites_enabled }}/{{ full_front_hostname }}.conf"
    state: link
  notify: restart nginx

- name: Remove default nginx site
  file:
    path: "{{ nginx_sites_enabled }}/default"
    state: absent
  notify: restart nginx 