---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy vue frontend configuration
  template:
    src: ./templates/vue.conf.j2
    dest: /etc/nginx/sites-available/vue
    mode: '0644'
  notify: restart nginx

- name: Copy mongo configuration
  template:
    src: ./templates/mongodb.conf.j2
    dest: /etc/nginx/sites-available/mongodb
    mode: '0644'
  notify: restart nginx
